# Makefile for Go-Hugo website

# Build the website
build:
	hugo -d ./module1_task1/dist
# Clean up the build directory
clean:
	rm -r dist/*

# Create a new blog post
post:
	hugo new posts/$(POST_NAME).md
/bin/bash: q : commande introuvable
