name: module3_task0
on:
  push:
  schedule:
    - cron: "0 0 1 * *"
jobs:
  check_make:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install
        run: |
          cd module3_task1
          ./setup.sh
