name: module3_task0
on: 
  push:
  schedule:
    - cron: '9 9 * * *'
jobs:
  check_make:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: help me to make help!
        run: |
          cd module3_task0
          make help


